{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.",
  "ExceptionType": "System.Data.Entity.Validation.DbEntityValidationException",
  "StackTrace": "  at System.Data.Entity.Internal.InternalContext.SaveChangesAsync (System.Threading.CancellationToken cancellationToken) [0x0003b] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 \n  at System.Data.Entity.Internal.LazyInternalContext.SaveChangesAsync (System.Threading.CancellationToken cancellationToken) [0x0000f] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 \n  at System.Data.Entity.DbContext.SaveChangesAsync (System.Threading.CancellationToken cancellationToken) [0x00006] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 \n  at System.Data.Entity.DbContext.SaveChangesAsync () [0x00006] in <b7b192e5a05f4f14a14aa0d5b14aeeeb>:0 \n  at EBook.Controllers.CustomerController.UpdateUser (EBook.Models.Customer data) [0x00036] in <c0703bd9cc8441c39cd3e43cb476ce01>:0 \n  at System.Threading.Tasks.TaskHelpersExtensions.CastToObject[T] (System.Threading.Tasks.Task`1[TResult] task) [0x0005b] in <4f8d88aa02d546f6963914471854cb7c>:0 \n  at System.Web.Http.Controllers.ApiControllerActionInvoker.InvokeActionAsyncCore (System.Web.Http.Controllers.HttpActionContext actionContext, System.Threading.CancellationToken cancellationToken) [0x000ab] in <4f8d88aa02d546f6963914471854cb7c>:0 \n  at System.Web.Http.Controllers.ActionFilterResult.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x00109] in <4f8d88aa02d546f6963914471854cb7c>:0 \n  at System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00152] in <4f8d88aa02d546f6963914471854cb7c>:0 "
}